# Generated by Django 5.1.3 on 2024-12-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikiApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulowiki",
            name="tema_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wikiApp.temawiki",
            ),
        ),
    ]
